name = "SunFounderRobotHat"
uuid = "6a6ad20d-f957-4727-a370-6c9aea3507ca"
authors = ["Fredrik Bagge Carlson"]
version = "1.0.0-DEV"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
